Ali implement progress bar
dynamic11/wet-react pull request #26
Opened 2022-01-21 20:24 UTC by alphaoreo

Adding the ProgressBar component and its stories to the master branch

2022-01-21 22:06 UTC, dynamic11 commented
@alphaoreo Prettier seems to be failing. Please check what file is causing the error and fix

2022-01-21 22:32 UTC, alphaoreo commented
> @alphaoreo Prettier seems to be failing. Please check what file is causing the error and fix

I believe I found the file causing the problem and have fixed it.

2022-01-24 18:45 UTC, dynamic11 requested changes
Please see my requested changes and we need to write tests

2022-01-24 18:45 UTC, dynamic11 commented on src/components/ProgressBar/ProgressBar.tsx
> +  visuallyHidden?: boolean;
rename to isLabelHidden

2022-01-24 18:45 UTC, dynamic11 commented on src/components/ProgressBar/ProgressBar.tsx
> +    className={className}
move classname above rest

2022-01-24 18:45 UTC, dynamic11 commented on src/components/ProgressBar/ProgressBar.tsx
> +    visuallyHidden={visuallyHidden}
update this variable name (see above)

2022-01-24 21:48 UTC, dynamic11 approved these changes
LGTM 🚀

2022-01-24 21:52 UTC, merged