[NEW] Implement Jumbotron Component
dynamic11/wet-react pull request #60
Opened 2022-02-15 13:26 UTC by alphaoreo

⭐ **New Features:**

- Implemented Jumbotron Component
- Added testing for Jumbotron Component

2022-02-15 16:48 UTC, Rizvida1 requested changes

2022-02-15 22:11 UTC, alphaoreo commented on src/components/Jumbotron/Jumbotron.tsx
> +  const finalStyle = `jumbotron ${style}`;
Sorry I did not see this but it is done now.

2022-02-15 23:12 UTC, Rizvida1 approved these changes
Looks good!

2022-02-16 14:52 UTC, dynamic11 reviewed
put jumbotron doesn't seem to match the on the wet website. is this expected?

2022-02-16 15:33 UTC, alphaoreo commented
> put jumbotron doesn't seem to match the on the wet website. is this expected?

Should I replace the div that makes a jumbotron with a section tag?

2022-02-17 17:00 UTC, dynamic11 commented
> > put jumbotron doesn't seem to match the on the wet website. is this expected?
> 
> Should I replace the div that makes a jumbotron with a section tag?

If they are using section then so should we 🔍

2022-02-23 22:12 UTC, merged